# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI - Unit Tests & Linting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Install dependencies
      run: yarn install

    - name: Bundle
      run: node bundler.js bin/assets bin/views/* --svgo --gzip 6
